# AUTO-GENERATED FILE — Regenerate with: make gen
"""Lazy-import manifest — single source of truth for flext_tests._utilities.__init__.py.

Generated by ``make gen``. The package initializer consumes only this module for
lazy (PEP 562) import access; sibling ``__all__`` discovery is the upstream source.
"""

from __future__ import annotations

LAZY_MODULES: dict[str, tuple[str, ...]] = {
    ".container": ("FlextTestsContainerHelpersUtilitiesMixin",),
    ".files": ("FlextTestsFilesUtilitiesMixin",),
    ".generic": ("FlextTestsGenericHelpersUtilitiesMixin",),
    ".handler": ("FlextTestsHandlerHelpersUtilitiesMixin",),
    ".make": ("FlextTestsMakeUtilitiesMixin",),
    ".make_contract": ("FlextTestsMakeContractUtilitiesMixin",),
    ".make_parsing": ("FlextTestsMakeParsingUtilitiesMixin",),
    ".make_registry": ("FlextTestsMakeRegistryUtilitiesMixin",),
    ".make_rendering": ("FlextTestsMakeRenderingUtilitiesMixin",),
    ".matchers": ("FlextTestsMatchersUtilities", "tm"),
    ".payload": ("FlextTestsPayloadUtilities",),
    ".result": ("FlextTestsResultUtilitiesMixin",),
    ".settings": ("FlextTestsConfigHelpersUtilitiesMixin",),
    ".testcontext": ("FlextTestsTestContextUtilitiesMixin",),
    ".validator": ("FlextTestsValidatorUtilitiesMixin",),
}


LAZY_ALIAS_GROUPS: dict[str, tuple[tuple[str, str], ...]] = {}


CHILD_MODULE_PATHS: tuple[str, ...] = ("._files", "._matchers")


EXCLUDED_LAZY_NAMES: tuple[str, ...] = ()


PUBLIC_EXPORTS: tuple[str, ...] = (
    "FlextTestsConfigHelpersUtilitiesMixin",
    "FlextTestsContainerHelpersUtilitiesMixin",
    "FlextTestsFilesUtilitiesMixin",
    "FlextTestsGenericHelpersUtilitiesMixin",
    "FlextTestsHandlerHelpersUtilitiesMixin",
    "FlextTestsMakeContractUtilitiesMixin",
    "FlextTestsMakeParsingUtilitiesMixin",
    "FlextTestsMakeRegistryUtilitiesMixin",
    "FlextTestsMakeRenderingUtilitiesMixin",
    "FlextTestsMakeUtilitiesMixin",
    "FlextTestsMatchersUtilities",
    "FlextTestsPayloadUtilities",
    "FlextTestsResultUtilitiesMixin",
    "FlextTestsTestContextUtilitiesMixin",
    "FlextTestsValidatorUtilitiesMixin",
    "_files",
    "_matchers",
    "tm",
)
