# AUTO-GENERATED FILE — Regenerate with: make gen
"""Lazy-import manifest — single source of truth for flext_tests._utilities._files.__init__.py.

Generated by ``make gen``. The package initializer consumes only this module for
lazy (PEP 562) import access; sibling ``__all__`` discovery is the upstream source.
"""

from __future__ import annotations

LAZY_MODULES: dict[str, tuple[str, ...]] = {
    "._assertions": ("FlextTestsFilesAssertionsMixin",),
    "._batch": ("FlextTestsFilesBatchMixin",),
    "._comparison_parts.comparison_part_02": ("FlextTestsFilesComparisonMixin",),
    "._contexts": ("FlextTestsFilesContextsMixin",),
    "._creation_parts.creation_part_03": ("FlextTestsFilesCreationMixin",),
    "._info": ("FlextTestsFilesInfoMixin",),
    "._lifecycle": ("FlextTestsFilesLifecycleMixin",),
    "._reading": ("FlextTestsFilesReadingMixin",),
}


LAZY_ALIAS_GROUPS: dict[str, tuple[tuple[str, str], ...]] = {}


CHILD_MODULE_PATHS: tuple[str, ...] = (
    "._comparison_parts",
    "._creation_parts",
)


EXCLUDED_LAZY_NAMES: tuple[str, ...] = ()


PUBLIC_EXPORTS: tuple[str, ...] = (
    "FlextTestsFilesAssertionsMixin",
    "FlextTestsFilesBatchMixin",
    "FlextTestsFilesComparisonMixin",
    "FlextTestsFilesContextsMixin",
    "FlextTestsFilesCreationMixin",
    "FlextTestsFilesInfoMixin",
    "FlextTestsFilesLifecycleMixin",
    "FlextTestsFilesReadingMixin",
    "_comparison_parts",
    "_creation_parts",
)
