# AUTO-GENERATED FILE — Regenerate with: make gen
"""Lazy-import manifest — single source of truth for flext_tests._utilities._files.__init__.py.

Generated by ``make gen``. The package initializer consumes only this module for
lazy (PEP 562) import access; sibling ``__all__`` discovery is the upstream source.
"""

from __future__ import annotations

LAZY_MODULES: dict[str, tuple[str, ...]] = {

    "._assertions": (

        "FlextTestsFilesAssertionsMixin",

    ),

    "._batch": (

        "FlextTestsFilesBatchMixin",

    ),

    "._comparison": (

        "FlextTestsFilesComparisonMixin",

    ),

    "._contexts": (

        "FlextTestsFilesContextsMixin",

    ),

    "._creation": (

        "FlextTestsFilesCreationMixin",

    ),

    "._info": (

        "FlextTestsFilesInfoMixin",

    ),

    "._lifecycle": (

        "FlextTestsFilesLifecycleMixin",

    ),

    "._reading": (

        "FlextTestsFilesReadingMixin",

    ),

}


LAZY_ALIAS_GROUPS: dict[str, tuple[tuple[str, str], ...]] = {}


CHILD_MODULE_PATHS: tuple[str, ...] = ()


EXCLUDED_LAZY_NAMES: tuple[str, ...] = ()


PUBLIC_EXPORTS: tuple[str, ...] = (

    "FlextTestsFilesAssertionsMixin",

    "FlextTestsFilesBatchMixin",

    "FlextTestsFilesComparisonMixin",

    "FlextTestsFilesContextsMixin",

    "FlextTestsFilesCreationMixin",

    "FlextTestsFilesInfoMixin",

    "FlextTestsFilesLifecycleMixin",

    "FlextTestsFilesReadingMixin",

)
