# AUTO-GENERATED FILE — Regenerate with: make gen
"""Lazy-import manifest — single source of truth for flext_tests._validator.__init__.py.

Generated by ``make gen``. The package initializer consumes only this module for
lazy (PEP 562) import access; sibling ``__all__`` discovery is the upstream source.
"""

from __future__ import annotations

LAZY_MODULES: dict[str, tuple[str, ...]] = {
    "._orchestration_parts.validator_part_02": ("FlextTestsValidator",),
    ".bypass": ("FlextValidatorBypass",),
    ".imports": ("FlextValidatorImports",),
    ".layer": ("FlextValidatorLayer",),
    ".markdown": ("FlextValidatorMarkdown",),
    ".models": ("FlextTestsValidatorModels",),
    ".settings": ("FlextValidatorSettings",),
    ".tests": ("FlextValidatorTests",),
    ".types": ("FlextValidatorTypes",),
}


LAZY_ALIAS_GROUPS: dict[str, tuple[tuple[str, str], ...]] = {}


CHILD_MODULE_PATHS: tuple[str, ...] = ("._orchestration_parts",)


EXCLUDED_LAZY_NAMES: tuple[str, ...] = ()


PUBLIC_EXPORTS: tuple[str, ...] = (
    "FlextTestsValidator",
    "FlextTestsValidatorModels",
    "FlextValidatorBypass",
    "FlextValidatorImports",
    "FlextValidatorLayer",
    "FlextValidatorMarkdown",
    "FlextValidatorSettings",
    "FlextValidatorTests",
    "FlextValidatorTypes",
    "_orchestration_parts",
)
