# AUTO-GENERATED FILE — Regenerate with: make gen
"""Lazy-import manifest — single source of truth for flext_tests.__init__.py.

Generated by ``make gen``. The package initializer consumes only this module for
lazy (PEP 562) import access; sibling ``__all__`` discovery is the upstream source.
"""

from __future__ import annotations

LAZY_MODULES: dict[str, tuple[str, ...]] = {
    "._config": ("config",),
    "._settings": ("settings",),
    ".base": (
        "FlextTestsCase",
        "FlextTestsServiceBase",
        "s",
    ),
    ".constants": (
        "FlextTestsConstants",
        "c",
    ),
    ".docker": (
        "FlextTestsDocker",
        "tk",
    ),
    ".domains": (
        "FlextTestsDomains",
        "td",
    ),
    ".files": (
        "FlextTestsFiles",
        "tf",
    ),
    ".models": (
        "FlextTestsModels",
        "m",
    ),
    ".protocols": (
        "FlextTestsProtocols",
        "p",
    ),
    ".tmatchers": (
        "FlextTestsMatchersUtilities",
        "tm",
    ),
    ".typings": (
        "FlextTestsTypes",
        "t",
    ),
    ".utilities": (
        "FlextTestsUtilities",
        "u",
    ),
    ".validator": (
        "FlextTestsValidator",
        "tv",
    ),
    "flext_infra": (
        "d",
        "e",
        "h",
        "r",
        "x",
    ),
}


LAZY_ALIAS_GROUPS: dict[str, tuple[tuple[str, str], ...]] = {}


CHILD_MODULE_PATHS: tuple[str, ...] = ()


EXCLUDED_LAZY_NAMES: tuple[str, ...] = ()


PUBLIC_EXPORTS: tuple[str, ...] = (
    "FlextTestsCase",
    "FlextTestsConstants",
    "FlextTestsDocker",
    "FlextTestsDomains",
    "FlextTestsFiles",
    "FlextTestsMatchersUtilities",
    "FlextTestsModels",
    "FlextTestsProtocols",
    "FlextTestsServiceBase",
    "FlextTestsTypes",
    "FlextTestsUtilities",
    "FlextTestsValidator",
    "__author__",
    "__author_email__",
    "__description__",
    "__license__",
    "__title__",
    "__url__",
    "__version__",
    "__version_info__",
    "c",
    "config",
    "d",
    "e",
    "h",
    "m",
    "p",
    "r",
    "s",
    "settings",
    "t",
    "td",
    "tf",
    "tk",
    "tm",
    "tv",
    "u",
    "x",
)
