# AUTO-GENERATED FILE — Regenerate with: make gen
"""Lazy-import manifest — single source of truth for flext_tests._models.__init__.py.

Generated by ``make gen``. The package initializer consumes only this module for
lazy (PEP 562) import access; sibling ``__all__`` discovery is the upstream source.
"""

from __future__ import annotations

LAZY_MODULES: dict[str, tuple[str, ...]] = {
    "._filesystem_parts.filesystem_part_02": ("FlextTestsFilesystemModelsMixin",),
    "._matchers_parts.matchers_part_03": ("FlextTestsMatchersModelsMixin",),
    ".base": ("FlextTestsBaseModelsMixin",),
    ".batch": ("FlextTestsBatchModelsMixin",),
    ".docker": ("FlextTestsDockerModelsMixin",),
    ".domains": ("FlextTestsDomainModelsMixin",),
    ".make": ("FlextTestsMakeModelsMixin",),
    ".validator": ("FlextTestsValidatorModelsMixin",),
}


LAZY_ALIAS_GROUPS: dict[str, tuple[tuple[str, str], ...]] = {}


CHILD_MODULE_PATHS: tuple[str, ...] = (
    "._filesystem_parts",
    "._matchers_parts",
)


EXCLUDED_LAZY_NAMES: tuple[str, ...] = ()


PUBLIC_EXPORTS: tuple[str, ...] = (
    "FlextTestsBaseModelsMixin",
    "FlextTestsBatchModelsMixin",
    "FlextTestsDockerModelsMixin",
    "FlextTestsDomainModelsMixin",
    "FlextTestsFilesystemModelsMixin",
    "FlextTestsMakeModelsMixin",
    "FlextTestsMatchersModelsMixin",
    "FlextTestsValidatorModelsMixin",
    "_filesystem_parts",
    "_matchers_parts",
)
